### ISSUE TITLE
Dataset for running example

### ISSUE THREAD

**Issue by vikramkalabi** [Brummi/MonoRec#1]
```
We provide a sample from the KITTI Odometry test set and a script to run MonoRec on it in example/. To download the pretrained model  ...
```

As mentioned in the  README, is there a link to the sample from the KITTI odometry dataset?

**Comment by Brummi** [comment]
Thank you for raising this issue! 
The sample data was meant to be in the repository itself, but was not pushed with the code by mistake.
I just added it. Could you please let me know if it works for you now?

**Comment by vikramkalabi** [comment]
It works! Thank you for the quick response. Appreciate your amazing work.
