### ISSUE TITLE
Clarification regarding mask module

### ISSUE THREAD

**Issue by testingshanu** [Brummi/MonoRec#10]
I wanted to clarify the following:

1. What type of information does stereo image add to the monorec network?
2. Is it possible to train the end to end model only using monocular images ?
2. Is it possible to train only the mask module only using monocular images ?

**Comment by nynyg** [comment]
I will try to answer your questions in the following:

1. The stereo images make the depth training more accurate, are crucial for the mask module refinement, and are needed for generating the auxiliary masks.
2. For the depth module, yes, for the mask module, as I mentioned above, we need the stereo images for the mask module refinement and generating auxiliary masks.
3.  Please refer to 2.

Thanks
