### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by yingzhow** [Brummi/MonoRec#11]
Run "python train_monorec.py --config configs/train/monorec/monorec_mask.json --options stereo"

File "/home/user/monorec/MonoRec-main-test/data_loader/kitti_odometry_dataset.py", line 67, in __init__
    with open(self.dataset_dir / "sequences" / sequence / (index_mask_name + ".json")) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/dataset/sequences/01/index_mask.json'

**Comment by Brummi** [comment]
Oh, thank you very much for pointing this out!
This is indeed a part of the data I forgot to upload.

Will do this in a few hours!
Thanks again!

**Comment by Brummi** [comment]
[index_masks.zip](https://github.com/Brummi/MonoRec/files/6987985/index_masks.zip)

For now, these are the files required, so that you can start the training. You can simply unpack them in the dataset directory (just like the other zip files).

Will properly upload it to the website soon.

**Comment by Brummi** [comment]
The files have now been uploaded to the official website and there is a link to them in the ReadMe.

**Comment by yingzhow** [comment]
Thank you so much ~
