### ISSUE TITLE
example script list index error

### ISSUE THREAD

**Issue by caisilus** [Brummi/MonoRec#14]
I was trying to run the example script, but ran into an error:

    Traceback (most recent call last):
    File "test_monorec.py", line 41, in <module>
    batch, depth = dataset.__getitem__(index)
    File "../data_loader/kitti_odometry_dataset.py", line 252, in __getitem__
    keyframe_pose = torch.tensor(dataset.poses[index + self._offset], dtype=torch.float32)
    IndexError: list index out of range
I found out that dataset poses for sequence 07 is an empty list. In this code below in **kitti_odometry_dataset.py** string constant is "poses_dvso". However, examples poses dir has name "poses_dso".

    if self.use_dso_poses:
        for dataset in self._datasets:
              dataset.pose_path = self.dataset_dir / "poses_dvso"
              dataset._load_poses()
It seems that changing the constant to "poses_dso" fixes the error.

**Comment by nynyg** [comment]
Hi @caisilus, thanks for pointing it out!
Actually, I just did a fix on that right before you posting the issue: https://github.com/Brummi/MonoRec/commit/f648ed7b8a93668708cb28d68a54853590d88428.

Could you please check if it works for you?

**Comment by caisilus** [comment]
> Hi @caisilus, thanks for pointing it out! Actually, I just did a fix on that right before you posting the issue: [f648ed7](https://github.com/Brummi/MonoRec/commit/f648ed7b8a93668708cb28d68a54853590d88428).
> 
> Could you please check if it works for you?

Hello @Yelen719, thank you for the answer!
It seems that the problem is still relevant. In the *example/data/kitti* folder, there is only a folder named "poses_**dso**", and no folder for the path "example/data/kitti/poses_**dvso**"
In [f648ed7](https://github.com/Brummi/MonoRec/commit/f648ed7b8a93668708cb28d68a54853590d88428) you changed string constant to the value "poses_**dvso**" that doesn't match the name of the folder (poses_**dso**). Should I download any **dvso** poses or the existing folder should be renamed to "poses_**dvso**"?

**Comment by caisilus** [comment]
I renamed string to the "poses_dso" and that worked for me. I am not really into computer vision and don't know the difference between dso and dvso, but it is confusing that the parameter use_**dso**_poses actually requires folder names **dvso**_poses

**Comment by nynyg** [comment]
Sorry for the mistake.

The folder `example/data/kitt/poses_dso` should be renamed to `example/data/kitt/poses_dvso` in this case.
I've pushed the fix. Please let us know if you face any other issues.

Best,
Nan

**Comment by caisilus** [comment]
Thanks, that helps!
