### ISSUE TITLE
How to prepare the 'image_depth_annotated' dataset?

### ISSUE THREAD

**Issue by ca1773130n** [Brummi/MonoRec#15]
Hi, thank you for sharing your great work.

I can create point clouds using create_pointcloud.py with 'image_depth_sparse' folder (downloaded DVSO) as depth_folder.
But I'm not sure this is correct.
Do I need to make image_depth_annotated images by myself?

Thanks in advance.

**Comment by Brummi** [comment]
Hi, thank you very much for using our work!

The point cloud creation script uses the depth outputs of the network and not the depth ground truth. The problem you are describing is a result of the implementation of our dataloaders (It always expects some depth ground truth). 

Regardless of whether you use image_depth_sparse or image_depth_annotated as depth ground truth, the output point cloud does not change.

Best,
Felix
