### ISSUE TITLE
What's the correspondence between KITTI raw data and KITTI Odometry?

### ISSUE THREAD

**Issue by guangkaixu** [Brummi/MonoRec#16]
Hi, thanks for your great contribution to 3d reconstruction.

For KITTI Odometry dataset, we can download RGB images from the official website, which are named by sequence number. But how can we get "the improved ground truth depth" mentioned in the README.md, which are named like "2011_09_26_drive_0001". What's the correspondence between them.

Thanks a lot.

**Comment by Brummi** [comment]
Hi, thank you very much for your interest in MonoRec!

You can simply run the [data_loader/scripts/preprocess_kitti_extract_annotated_depth.py](https://github.com/Brummi/MonoRec/blob/main/data_loader/scripts/preprocess_kitti_extract_annotated_depth.py) script, which associates the improved ground truth with the correct sequences. The script contains a dictionary with those correspondences.
