### ISSUE TITLE
poses and dso_poses

### ISSUE THREAD

**Issue by yingzhow** [Brummi/MonoRec#17]
1. In the training stage, do you only use the **dso_poses**?  What the role of **poses**?
2. If I use the **ScanNet** dataset for training, what should I prepare?
3. The color images of ScanNet is monocular, If I only train the **depth moudule**, is that ok?
4. Can I use the lidar depth (annotated) for training? I mean just have one set of depth gt and pose, is that ok?

**Comment by Brummi** [comment]
Hi, 
thanks for being interested in our work!

1. **poses** are the poses that come with KITTI odometry. We experimented with using them for training, however, they produce worse results than when using the poses from dvso / dso.
2. Most importantly, you require the camera pose and intrinsics for every frame. Additionally, our configuration uses a sparse depth map (from dvso) for every frame. However, this sparse depth map can be taken from anywhere.
3. The training requires sequences of frames. Rendering only one frame of a ShapeNet object will not suffice, sorry!
4. You can use lidar depth for training. However, then the method does not _only_ on data from a monocular camera anymore.
