### ISSUE TITLE
the setup of KITTI dataset

### ISSUE THREAD

**Issue by ZheningHuang** [Brummi/MonoRec#18]
Hi, I was trying to **reproduce the point clouds** for **KITTI Odometry** dataset with the pre-trained model you provided. I am a bit confused about **the setup of KITTI dataset for this**.

You mentioned 

> **_"To setup KITTI Odometry, download the color images and calibration files from the official website (around 145 GB)._**

 

I wonder if this 145 GB is comprised of:  
**Download odometry data set (color, 65 GB)
Download odometry data set (velodyne laser data, 80 GB)?**  at the  [official website](http://www.cvlibs.net/datasets/kitti/eval_odometry.php). 

For the task I described, (not to train the model, just to reproduce the point clouds), I have done the following:
1. download odometry data set, including `color (65 GB)` and `calibration files (1 MB)` from the
2. Replace the` calib.txt` and `times.txt` files in `color (65 GB)` with `calib.txt` and `times.txt` files in `calibration files (1 MB)`
3. Download the pre-trained final model by running `download_model.sh`
From the error I got, it seems I still missing  '`../../../data/dataset/sequences/00/image_depth_annotated`' 

Would be really appreciate it if you could let me know how can I got this. If possible, also correct me if I did anything wrong.

Thanks for your help

**Comment by yxt7979** [comment]
Hi! How did you solve the problem? I just want to rebuild the cloud (no training required) too.   Do I have to download the entire dataset? Can you share your steps~ Thanks a lot!!
