### ISSUE TITLE
Multi card training

### ISSUE THREAD

**Issue by ChauChorHim** [Brummi/MonoRec#23]
Hi!
The training process takes longer than I expect. Is it possible to use multi card in one machine to train the model?
I tried to add --device in the args but still only one card is working.
Thank you!

**Comment by Brummi** [comment]
Hi,
sorry for the late reply!
Only the bootstrap models can be trained on multiple GPUs. Here, you have to specify it in the config files as `n_gpu`.
Best,
Felix
