### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'att_cp_loc'

### ISSUE THREAD

**Issue by jing-yao** [Brummi/MonoRec#24]
Hi.  Thanks for your job. When I run the last training 
python train_monorec.py --config configs/train/monorec/monorec_depth_ref.json --options stereo stereo_repr ，
there was a TypeError:

> Traceback (most recent call last):
>   File "train_monorec.py", line 70, in <module>
>     main(config, config.args.options)
>   File "train_monorec.py", line 25, in main
>     model = config.initialize('arch', module_arch)
>   File "/home/ubuntu/space/MonoRec-main/utils/parse_config.py", line 81, in initialize
>     return getattr(module, module_name)(*args, **module_args)
> TypeError: __init__() got an unexpected keyword argument 'att_cp_loc'

And whatever I run any training , there often appears:

> Ground truth poses are not avaialble for sequence 01.
> Ground truth poses are not avaialble for sequence 02.
> Ground truth poses are not avaialble for sequence 06.
> Ground truth poses are not avaialble for sequence 08.
> Ground truth poses are not avaialble for sequence 09.
> Ground truth poses are not avaialble for sequence 10.
> Ground truth poses are not avaialble for sequence 00.
> Ground truth poses are not avaialble for sequence 04.
> Ground truth poses are not avaialble for sequence 05.
> Ground truth poses are not avaialble for sequence 07.

**Comment by ChauChorHim** [comment]
Hi jingyao, 
you can fix it by replacing the 'att_cp_loc' in monorec_depth_ref.json with 'mask_cp_loc'.

**Comment by ChauChorHim** [comment]
Hi @jing-yao ,
you can fix it by replacing the 'att_cp_loc' in monorec_depth_ref.json with 'mask_cp_loc'.
