### ISSUE TITLE
moving mask generation

### ISSUE THREAD

**Issue by bpwl0121** [Brummi/MonoRec#25]
Hi Felix, 

Thank you very much for opening the source code! 
could you please provide the code about how to generate the moving mask？

thanks!

**Comment by Brummi** [comment]
Hi,
unfortunately, the code to generate the moving object masks is not polished and well document. This is why we have not released it. However, if you reach out to me via email, I can provide you with the raw code (it is not exactly the version from the paper though).
Best,
Felix

**Comment by bpwl0121** [comment]
Hi Felix,

Thank you very much for providing the raw code, even if it is not well documented!
Email: wenliang.peng@tum.de

Best,
Wenliang
