### ISSUE TITLE
Can MonoRec be trained on Kitti Raw Dataset with image squences?

### ISSUE THREAD

**Issue by kaixinbear** [Brummi/MonoRec#26]
Could this method accepth a squence of images as input and output absolute depth map or pseudo-lidar in camera coordinates?

**Comment by Brummi** [comment]
Hi!
Yes, it should indeed be possible to train this method on the raw dataset.
However, preparing the dataset might be a little tedious. In our experiments, we found that the poses that come with KITTI produce worse results than when we use poses from odometry systems like DSO or DVSO.
You can find the DSO repository here: https://github.com/JakobEngel/dso
Best,
Felix

**Comment by kaixinbear** [comment]
Could I reckon that good results can be obtained only when accurate odometry(ego motion) info were provided ?

**Comment by Brummi** [comment]
You are right. For this method, it is necessary that the pose information is sufficiently accurate.
