### ISSUE TITLE
Tool for  reconstructed scene visualization

### ISSUE THREAD

**Issue by HanzhiC** [Brummi/MonoRec#3]
Hi!

Thanks for this amazing job :)
I am wondering if you could kindly inform which tool you are using for the reconstructed scene visualization, it looks really cool !
Thanks!

**Comment by kxhit** [comment]
Hi @HanzhiC  Have you solved this issue? I opened the .ply files with softwares like meshlab but find no color info shows. I read the ply file and find the rgb info is in float type and the standard ply is uchar type. Could you let me know how do you resolve this problem? Thanks!

**Comment by HanzhiC** [comment]
Hi, actually you can maybe try to save it with Open3D, then the color informantion will be saved ;)

**Comment by Brummi** [comment]
@kxhit @HanzhiC 
Thanks for investigating this problem!
I also noticed that some viewers (for example meshlab) don't load the colors, even though they are stored in the file.

I will try to fix this issue at some point.

**Comment by kxhit** [comment]
Thanks! Looking forward to the updates!
Actually, I suppose the format of rgb should be uchar instead of float. So I figured it out by modifying the header and converting rgb from float to np.uint8, which is shown as follows. Hope it helps.

```
header = "ply\n" \
                 "format ascii 1.0\n" \
                 f"element vertex {length}\n" \
                 f"property float x\n" \
                 f"property float y\n" \
                 f"property float z\n" \
                 f"property uchar red\n" \
                 f"property uchar green\n" \
                 f"property uchar blue\n" \
                 f"end_header\n"
file.write(header)
points = np.array(self.data).reshape(-1,6)
for _, point in enumerate(points):
    file.writelines(
        [str(point[0]), ' ', str(point[1]), ' ', str(point[2]), ' ', str(np.uint8(point[3])), ' ', str(np.uint8(point[4])), ' ',
         str(np.uint8(point[5])), '\n'])
```

**Comment by Brummi** [comment]
I implemented a similar solution as @kxhit and explained it in #20 .
