### ISSUE TITLE
Usage of "--options" in training command

### ISSUE THREAD

**Issue by fengziyue** [Brummi/MonoRec#35]
Hi:

Thank you for the wonderful work, I have a question about the usage of the "--options" in training commands.
My understanding is the "--options" are used for the loss functions in "model/loss_functions/monorec_loss.py". but since the monorec_mask.json has defined the loss function as "mask_loss", which does not have the "stereo" option, why do we need to add "--options stereo" to train the mask module?
`python train_monorec.py --config configs/train/monorec/monorec_mask.json --options stereo`

Any clarification is greatly appreciated!

**Comment by Brummi** [comment]
Hi!

thanks for showing interest in our work. You are right, mask loss doesn't consider the stereo option.
The reason it is there is probably because I copy & pasted the options flag to every training.
For the mask bootstrap step, it can be removed.

Best,
Felix
