### ISSUE TITLE
Realtime

### ISSUE THREAD

**Issue by TuskAW** [Brummi/MonoRec#45]
Hello. I wanted to ask about how suitable MonoRec could be for realtime reconstruction. Any information will be greatly appreciated.

**Comment by Brummi** [comment]
Hi TuskAW,

thanks for your interest in our work!
In our experiments, we were able to get 10+ FPS on a 12GB Titan. This
assumes that you data loading takes very little time. I am sure this could
be optimized further. Also, the configuration plays a big role (we use 32
depth planes, but you could try less)

Best,
Felix

TuskAW ***@***.***> schrieb am Fr., 14. Okt. 2022, 00:07:

**Comment by TuskAW** [comment]
Thanks for the quick reply. My use case would be to use realtime video from a zed/real sense camera and reconstruct the 3D scene, including dynamic objects, such as cars, people, etc. I would have the camera in a fixed location at first, but will want to have it on a moving platform. The hardware would not be a problem; however, frame rate would be important. 10 fps may be a good starting point, but ideally, 30 fps would be the sweet spot for my project.
