### ISSUE TITLE
 How to run on my own data

### ISSUE THREAD

**Issue by JustC0deIt** [Brummi/MonoRec#46]
Hi.First of all, thank you for your efforts, and I am also surprised by the effect.
If I want to make predictions in my own data, how should I get the configs

**Comment by Brummi** [comment]
Hi, 
thank you for your interest!
What kind of data do you have available?
For inference, you require 1. images (or video from which you can extract frames) 2. camera calibration (projection matrix) and 3. camera poses.
Some of this can be obtained from SLAM systems like DSO or ORB-SLAM.

Best,
Felix

**Comment by JustC0deIt** [comment]
thanks for your time,now i have sequential pictures(RGB) extracted from video,and can i get the camera poses from DVSO or other algorithm？I used to get them by SuperPoint / SuperGlue inaccurately

**Comment by Brummi** [comment]
Yes, I have found that for video (e.g. autonomous driving), SLAM methods like DSO and ORB-SLAM work great (better than stuff like Colmap)
