### ISSUE TITLE
Using ORB-SLAM as input for live reconstruction?

### ISSUE THREAD

**Issue by danielj-genesis** [Brummi/MonoRec#49]
I've seen it suggested on other issues that this pairs well orb-slam. Would it be possible to do dense reconstruction in real time from Monocular ORB-SLAM output? The orb slam trajectory format looks different from the one used in the demo here.

**Comment by Brummi** [comment]
Hi Danielj,

thanks for your interest in our work!
I dont see why it wouldn't be possible.

In my current project, I am using poses computed from ORB-SLAM3 for KITTI Raw, and it works just fine.
In ORB-SLAM3, there is a function already implemented to export poses into the KITTI format.

Hope this helps!
Best,
Felix
