### ISSUE TITLE
No module named 'model.layers'

### ISSUE THREAD

**Issue by liushu309** [Brummi/MonoRec#5]
when I run the scripts 'cd example' and 'python test_example.py', the following error occurred:
Traceback (most recent call last):
  File "test_monorec.py", line 10, in <module>
    from data_loader.kitti_odometry_dataset import KittiOdometryDataset
  File "../data_loader/kitti_odometry_dataset.py", line 13, in <module>
    from utils import map_fn
  File "../utils/__init__.py", line 2, in <module>
    from .ply_utils import *
  File "../utils/ply_utils.py", line 5, in <module>
    from model.layers import Backprojection
ModuleNotFoundError: No module named 'model.layers'

I don't know why, and the test_example.py line 7-8 already has the scripts:
import sys
sys.path.append("..")

**Comment by Brummi** [comment]
Hi! Thank you for being interested in the project!
Did you already change anything in the code or is this the original repository? (Maybe do a git status)
When I do a fresh clone of the repository and run cd example and python test_monorec.py, I don't get any errors.

**Comment by liushu309** [comment]
> Hi! Thank you for being interested in the project!
> Did you already change anything in the code or is this the original repository? (Maybe do a git status)
> When I do a fresh clone of the repository and run cd example and python test_monorec.py, I don't get any errors.

Hi, Thank you for sharing your amazing work. When I do a fresh clone of the repository, and run 'conda env create -f environment.yml' before 'cd example and python test_monorec.py', I successfully got the result, I am not sure python3.7 will conducting this error.Thank you for your patiently answer.
