### ISSUE TITLE
How to train with only Monocular data sequence?

### ISSUE THREAD

**Issue by Owen-Liuyuxuan** [Brummi/MonoRec#6]
As I was reading the paper, it seems that static stereo plays quite a role in the training process?

**Comment by Brummi** [comment]
Hi,
thank you for being interested in the project!
Yes, during training we require stereo frames, otherwise there would be no training signal for moving objects. 
Inference runs only on mono frames.
Best,
Felix

**Comment by testingshanu** [comment]
@Brummi What does the "training signal" for moving objects indicate ?
