### ISSUE TITLE
run creat_pointcloud.py

### ISSUE THREAD

**Issue by wxlwhu** [Brummi/MonoRec#7]
Hi author:
I faced the following problem when running creat_pointcloud.py.

**Problem: 
RuntimeError: The NVIDIA driver on your system is too old.**

Environment on my computer:
Ubuntu 16.04 LTS, GEFORCE RTX 2060, CUDA 10.1, NVIDIA driver: 430.64. 

So, Would you please tell me the required environment config?
Expecting for your reply.

**Comment by Brummi** [comment]
Hi,
thank you for being interested in this paper!
Could you please let me know how you set up the python environment?
Did you use the provided environment.yml file?
Best,
Felix
